"""empty message

Revision ID: da08400a1c12
Revises: 8e47e83d1da7
Create Date: 2024-01-17 11:48:34.999028

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'da08400a1c12'
down_revision = '8e47e83d1da7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employee', schema=None) as batch_op:
        batch_op.drop_index('username')
        batch_op.drop_column('username')
        batch_op.drop_column('password')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employee', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password', mysql.VARCHAR(length=60), nullable=True))
        batch_op.add_column(sa.Column('username', mysql.VARCHAR(length=20), nullable=True))
        batch_op.create_index('username', ['username'], unique=False)

    # ### end Alembic commands ###
