"""empty message

Revision ID: f603a2b7a331
Revises: 25243e00764d
Create Date: 2024-01-07 12:16:53.601292

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f603a2b7a331'
down_revision = '25243e00764d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('timeoff', schema=None) as batch_op:
        batch_op.add_column(sa.Column('emp_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('emp_name', sa.String(length=120), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('timeoff', schema=None) as batch_op:
        batch_op.drop_column('emp_name')
        batch_op.drop_column('emp_id')

    # ### end Alembic commands ###
